### ISSUE TITLE
Broken properties

### ISSUE THREAD

**Issue by bart-degreed** [MindOnSite/FluentxApi#11]
- The `Minimum` and `Maximum` private properties in https://github.com/MindOnSite/FluentxApi/blob/master/src/Mos.xApi/Objects/InteractionActivities/NumericRange.cs are only assigned to, but never used.
- The `StringContent` private property in https://github.com/MindOnSite/FluentxApi/blob/master/src/Mos.xApi/Document.cs is never used.
- The `Updated` private property in https://github.com/MindOnSite/FluentxApi/blob/master/src/Mos.xApi/Document.cs is only assigned to, but never used.
- The `LanguageCode` public readonly property in https://github.com/MindOnSite/FluentxApi/blob/master/src/Mos.xApi/Objects/InteractionActivities/FillInInteractionActivity.cs is never assigned to.

**Comment by Gimly** [comment]
Moved the private properties to public and added the languageCode to the constructor to be able to set it.
