### ISSUE TITLE
Attachment json serialization issues: wrong property name camel-casing, null-serialization

### ISSUE THREAD

**Issue by erwindl0** [MindOnSite/FluentxApi#15]
Contrary to the other classes, Attachment.cs does not contain yet JsonProperty annotations.
As a consequence the JSON serialization has wrong property names.
It also exports null properties.

E.g. UsageType i.o. usageType. And similar for the other properties.
This leads to parsing errors on an LRS backend.

```
        "attachments": [
            {
                "UsageType": "http://id.tincanapi.com/attachment/supporting_media",
                "Display": {
                    "en-US": "Test Note"
                },
                "ContentType": "image/jpg",
                "Length": 219730,
                "Sha2": "5eddbaa46952f1bd8ac0a09631fa6530ca9077f82e81753702d3cea3ddcdee4b",
                "Description": null,
                "FileUrl": null
            }
        ]
```

should be:

```
        "attachments": [
            {
                "usageType": "http://id.tincanapi.com/attachment/supporting_media",
                "display": {
                    "en-US": "Test Note"
                },
                "contentType": "image/jpg",
                "length": 219730,
                "sha2": "5eddbaa46952f1bd8ac0a09631fa6530ca9077f82e81753702d3cea3ddcdee4b"
            }
        ]
```

cfr https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#example

**Comment by erwindl0** [comment]
we can prepare  a patch pull request if you accept those?

**Comment by Gimly** [comment]
@erwindl0 Sure thing!

**Comment by erwindl0** [comment]
created PR #16

**Comment by erwindl0** [comment]
Thanks @Gimly for accepting the PR!

Any idea when we would see the new version on nuget?

**Comment by Gimly** [comment]
@erwindl0 it's up on MyGet but unfortunately I'm having an issue with the NuGet deployment that I don't quite understand. I'll try to do fix that as soon as possible.

**Comment by Gimly** [comment]
@erwindl0 sorry it took some time, but the 0.9.0 with your PR has been pushed to NuGet. I'm closing this issue for now. Thanks for your work and don't hesitate to open new issues or send new changes.
