### ISSUE TITLE
Question: do you develop / take PRs

### ISSUE THREAD

**Issue by srijken** [MindOnSite/FluentxApi#8]
What the title says, is this actively being developed? Do you take PRs when something's missing / broken?

Haven't really tried the library yet, but I want to check this beforehand :)

**Comment by Gimly** [comment]
It's not actively developed right now because the project drifted and it's not actively used. But if there are issues opened I'll probably invest the time to fix them and will gladly merge PRs.

**Comment by srijken** [comment]
Great thanks! I'll start using it, if I run into something I'll let you know
